### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by champ** [lstrojny/php-cld#1]
Hi,

First of all, great iniciative! CLD rocks!!

What revision of the CLD are you using? I'm using 2e9f144ce4d1 and I get this error when running the tests: PHP Startup: Unable to load dynamic library 'xxxxx/php-cld/modules/cld.so' - xxxxx/php-cld/modules/cld.so: undefined symbol: _ZNSs4_Rep20_S_empty_rep_storageE in Unknown on line 0. Linking problem?

I've also tried using the latest revision() but that one doesn't install because of changes to/removal of DetectLanguageSummary.

/Hampus

**Comment by lstrojny** [comment]
Thanks for the report. Please try the latest GIT version against the latest HEAD of libcld.
