### ISSUE TITLE
PHP 5.4 only?

### ISSUE THREAD

**Issue by Qubitium** [lstrojny/php-cld#5]
Is the CLD extension only for php 5.4+?

Tested this with latest stable 5.3.8 on Scientific Linux 6.1 (RHEL6/CENTOS6) and got the following.
# 

PHP_SAPI    : cli
PHP_VERSION : 5.3.8
ZEND_VERSION: 2.3.0
PHP_OS      : Linux - Linux toast.com 2.6.32-131.17.1.el6.x86_64 #1 SMP Wed Oct 5 17:19:54 CDT 2011 x86_64
INI actual  : /root/php-cld/tmp-php.ini
More .INIs  :
CWD         : /root/php-cld
Extra dirs  :
# VALGRIND    : Not used
# TIME START 2011-11-22 07:02:37

PASS CLD\Language and CLD\Encoding [tests/cld-classes.phpt]
FAIL CLD\detect() basic behavior [tests/cld-detect_basic.phpt]
PASS CLD\detect() error behavior [tests/cld-detect_error.phpt]
FAIL CLD\detect() basic behavior [tests/cld-detect_variant1.phpt]
FAIL array CLD\Detector::detectLanguage(string text, bool isPlainText = true) [tests/cld-detector-detectLanguage.phpt]
PASS void CLD\Detector::setEncodingHint(int encodingHint) / int CLD\Detector::getEncodingHint() [tests/cld-detector-encodingHint.phpt]
PASS void CLD\Detector::setIncludeExtendedLanguages(bool true) / bool CLD\Detector::getIncludeExtendedLanguages() [tests/cld-detector-includeExtendedLanguages.phpt]
PASS void CLD\Detector::setLanguageHint(string language) / string CLD\Detector::getLanguageHint() [tests/cld-detector-languageHint.phpt]
PASS Test subclasses CLD\Detector [tests/cld-detector-subclass.phpt]
PASS void CLD\Detector::setTopLevelDomainHint(string tld) / string CLD\Detector::getTopLevelDomainHint() [tests/cld-detector-topLevelDomainHint.phpt]
PASS Test correct library invokation [tests/cld-invokation.phpt]
PASS ReflectionExtension::getName() for CLD\detect() [tests/cld-reflection-01.phpt]
XFAIL ReflectionExtension::getFunctions() for CLD\detect() [tests/cld-reflection-02.phpt]   XFAIL REASON: Namespaced functions cause ReflectionExtension to fail in PHP 5.3

PASS ReflectionFunction for CLD\detect() [tests/cld-reflection-03.phpt]
PASS ReflectionClass for CLD\Language and CLD\Encoding [tests/cld-reflection-04.phpt]
PASS Reflection for CLD\Detector [tests/cld-reflection-05.phpt]
# PASS Exception reflection [tests/cld-reflection-06.phpt]

TIME END 2011-11-22 07:02:37
# 
## TEST RESULT SUMMARY

Exts skipped    :    0
## Exts tested     :   36

Number of tests :   17                17
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    3 ( 17.6%) ( 17.6%)
Expected fail   :    1 (  5.9%) (  5.9%)
## Tests passed    :   13 ( 76.5%) ( 76.5%)
# Time taken      :    0 seconds
# 
## FAILED TEST SUMMARY

CLD\detect() basic behavior [tests/cld-detect_basic.phpt]
CLD\detect() basic behavior [tests/cld-detect_variant1.phpt]
# array CLD\Detector::detectLanguage(string text, bool isPlainText = true) [tests/cld-detector-detectLanguage.phpt]
# 
## EXPECTED FAILED TEST SUMMARY

ReflectionExtension::getFunctions() for CLD\detect() [tests/cld-reflection-02.phpt]  XFAIL REASON: Namespaced functions cause ReflectionExtension to fail in PHP 5.3
#

**Comment by lstrojny** [comment]
could you show me the test diffs?

**Comment by Qubitium** [comment]
## cld-detect_basic.diff

001+ array(2) {
001- array(1) {
013+   [1]=>
014+   array(4) {
015+     ["name"]=>
016+     string(7) "ENGLISH"
017+     ["code"]=>
018+     string(2) "en"
019+     ["reliable"]=>
020+     bool(true)
021+     ["bytes"]=>
022+     int(46)
023+   }
038- array(1) {
049+ array(2) {
050- }
051- ==DONE==
061+   [1]=>
062+   array(4) {
063+     ["name"]=>
064+     string(7) "ENGLISH"
065+     ["code"]=>
066+     string(2) "en"
067+     ["reliable"]=>
068+     bool(true)
069+     ["bytes"]=>
070+     int(13)
071+   }
072+ }
073+ ==DONE==[

## cld-detector-detectLanguage.diff

006+ array(2) {
006- array(1) {
018+   [1]=>
019+   array(4) {
020+     ["name"]=>
021+     string(7) "ENGLISH"
022+     ["code"]=>
023+     string(2) "en"
024+     ["reliable"]=>
025+     bool(true)
026+     ["bytes"]=>
027+     int(46)
028+   }
043- array(1) {
054+ array(2) {
055- }
056- ==DONE==
066+   [1]=>
067+   array(4) {
068+     ["name"]=>
069+     string(7) "ENGLISH"
070+     ["code"]=>
071+     string(2) "en"
072+     ["reliable"]=>
073+     bool(true)
074+     ["bytes"]=>
075+     int(13)
076+   }
077+ }
078+ ==DONE==

**Comment by Qubitium** [comment]
## cld-detect_variant1.diff

001+ array(2) {
001- array(1) {
013+   [1]=>
014+   array(4) {
015+     ["name"]=>
016+     string(7) "ENGLISH"
017+     ["code"]=>
018+     string(2) "en"
019+     ["reliable"]=>
020+     bool(true)
021+     ["bytes"]=>
022+     int(46)
023+   }
062- array(1) {
073+ array(2) {
074- }
075- ==DONE==
085+   [1]=>
086+   array(4) {
087+     ["name"]=>
088+     string(7) "ENGLISH"
089+     ["code"]=>
090+     string(2) "en"
091+     ["reliable"]=>
092+     bool(true)
093+     ["bytes"]=>
094+     int(32)
095+   }
096+ }
097+ ==DONE==

## cld-reflection-02.diff

002+   ["CLD\detect"]=>
003+   string(10) "CLD\detect"
002-   [0]=>
003-     string(12) "CLD\detect()"[

**Comment by lstrojny** [comment]
This looks like you have a newer version of the library which I don’t have tested till now. The PHP extension should work, just the tests are a little too strict.

**Comment by Qubitium** [comment]
Re-tested this on a Clean SL 6.1 (Centos 6.1) install and the extension works minus the same test errors which we assume to ignore. =)
