### ISSUE TITLE
Object vs Function access name diff

### ISSUE THREAD

**Issue by Qubitium** [lstrojny/php-cld#6]
Suggestion: unify the naming scheme for both function and object method name for "detect". Also fix example to reflect the correct method names.

Right now:

1) Function: detect()
2) Object: $d->detectLanguage();

New:

1) Function: detect()
2) Object: $d->detect();

**Comment by lstrojny** [comment]
Sorry for the long wait, I wouldn’t mind an alias for it. Patches welcome.

**Comment by mindon** [comment]
Should update the "Usage" in README first if no changes :)

**Comment by lstrojny** [comment]
Good point, fixed.
